services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      macvlan_net:
        ipv4_address: <static ip for qbittorrent>
    environment:
      TZ: '<timezone>'
      PUID: '<user id>'
      PGID: '<user group id>'
      WEBUI_PORT: '80'
      TORRENTING_PORT: '6881'
    volumes:
      - ./config:/config
      - <download dir on your device>:<download dir as seen by qbittorrent>
    restart: unless-stopped

networks:
  macvlan_net:
    external: true