services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    hostname: mealie
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.13
    volumes:
      - ./mealie:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      API_PORT: 80
      TZ: Asia/Kolkata
      BASE_URL: http://eat.mealie
      DAILY_SCHEDULE_TIME: 03:00
    restart: unless-stopped

networks:
  macvlan_net:
    external: true